# Generated by Django 5.1.6 on 2026-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_quiz_quizattempt_quizquestion_quizchoice_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
